---
title: "PSY 8712 Week 8 Project"
author: "Julia Hong"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    number_sections: true
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_dir = "../out")})
---

# **Reproducible Image and Online Resources**

An image of this project as of *`r Sys.Date()`* can be accessed by [clicking this link](https://mybinder.org).

An interactive web app is available by [clicking this link instead](https://shinyapp.io).

# **Script Settings and Resources**

```{r echo = FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
```

# **Data Import and Cleaning**

Import data from week3.csv, add labels for gender and condition, reverse code Q5

```{r echo = FALSE}
week8_tbl <- read_csv("../data/week3.csv", col_names = TRUE, col_types = cols(timeStart=col_datetime("%F %h:%M:%S"))) %>%
  mutate(
    gender = factor(gender, levels = c("M", "F"), labels = c("Male", "Female")),
    condition = factor(condition, levels = c("A", "B", "C"), labels = c("Block A", "Block B", "Control")),
    q5 = 6 - q5
  )
```

# **Visualization**

# **Analysis**